# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

schedules:
  - cron: "0 4 * * *"
    displayName: "Nightly - mlz bicep azure US Gov Cloud"
    branches:
      include:
        - main
    always: true

pool:
  vmImage: ubuntu-latest

variables:
  GServiceConnectionName: $(GAzureConnection)

jobs:
- job: AzureGov
  steps:
  - task: AzureCLI@2
    displayName: "Deploy MLZ - ASH"
    inputs:
      azureSubscription: $(GServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        datetime=$(date +%s) # gets the current date time as an epoch
        az deployment sub create \
          --name $(bDeploymentName) \
          --location $(GLocation) \
          --template-file $(TemplateFile) \
          --parameters resourcePrefix=$datetime
          
  - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
    displayName: 'Generate SBOM'
    inputs:
      BuildDropPath: '$(Build.ArtifactStagingDirectory)'  

  - task: AzureCLI@2
    displayName: "Clean up Resources"
    condition: always()
    inputs:
      azureSubscription: $(GServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az group list \
          --query "[].name" \
          --output tsv \
        | xargs -t -I % az group delete \
          --yes \
          --no-wait \
          --name %

  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish SBOM to Build Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'