# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: validate-build-bicep
on:
 push:
   branches:
      - main
   paths: 
    - '**.bicep'
 pull_request:
    branches:
    - main      
    paths: 
    - '**.bicep'
   
jobs:
  validate-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          find src/bicep/ -name modules -prune -o -name '*.bicep' -print -exec az bicep build --file '{}' \;
          find src/bicep/ -name modules -prune -o -name '*.json' -print -exec git add '{}' \;
          git commit -m "GitHub Action: Build Bicep to JSON"
          git push origin HEAD:"$GITHUB_HEAD_REF"
          git push
