# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: validate-bicep
on: 
  pull_request:
    branches:
      - main
      
    paths: 
    - '**.bicep'
  
jobs:
  validate-bicep:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps: 
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          find src/bicep/ -name modules -prune -o -name '*.bicep' -print -exec az bicep build --file '{}' \;