# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: validate-bicep
on: 
 push:
 pull_request:
    branches:
      - main
      
    paths: 
    - '**.bicep'
  
jobs:
  validate-bicep:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps: 
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          find src/bicep/ -name modules -prune -o -name *.bicep -print -exec az bicep build --file '{}' \;